export const browserClientViewPaths = new Set([
  "register",
  "home",
  "environment",
  "login?email=notarealemail@bitwarden.com",
  "account-switcher",
  "add-cipher",
  "tabs/vault",
  "tabs/send",
  "add-send",
  "tabs/generator",
  "generator-history",
  "tabs/settings",
  "account-security",
  "autofill",
  "notifications",
  "excluded-domains",
  "folders",
  "vault-settings",
  "export",
  "appearance",
  "about",
  "more-from-bitwarden",
  "premium",
]);

export const browserClientViewPathsRefreshUI = new Set(["lockV2", "trash"]);
